steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/synthetic-data-gen:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/synthetic-data-gen:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'synthetic-data-gen'
    - '--image'
    - 'gcr.io/$PROJECT_ID/synthetic-data-gen:$COMMIT_SHA'
    - '--region'
    - 'asia-northeast3'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '2Gi'
    - '--cpu'
    - '2'
    - '--concurrency'
    - '80'
    - '--max-instances'
    - '10'
    - '--timeout'
    - '3600'

images:
- gcr.io/$PROJECT_ID/synthetic-data-gen:$COMMIT_SHA